<?php

namespace Database\Seeders;

use App\Models\StockCode;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class StockCodeSeeder extends Seeder
{
    public function run(): void
    {
        $stockdata = [
            [
                'stock_code' => '000026583',
                'price_code' => 'FP',
                'item_name' => "COAT, MAN'S",
                'class' => 'A',
                'current_class' => 'A',
                'mnemonic_current' => 'TABASA',
                'pn_current' => 'RAIN COAT',
                'pn_global' => 'RAIN COAT',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000312207',
                'price_code' => 'FP',
                'item_name' => 'LUBRICATING OIL,MINERAL,STEAM CYLINDER',
                'class' => 'I',
                'current_class' => 'I',
                'mnemonic_current' => 'PERTAMIN',
                'pn_current' => 'MEDTIRAN SX  CI-4',
                'pn_global' => 'MEDTIRAN SX  CI-4',
                'wh' => 'OTS1',
                'uoi' => 'LITR'
            ],
            [
                'stock_code' => '000269548',
                'price_code' => 'FP',
                'item_name' => 'LUBRICATING OIL, HYDRAULIC',
                'class' => 'I',
                'current_class' => 'I',
                'mnemonic_current' => 'PERTAMIN',
                'pn_current' => 'TURALIK-XT46',
                'pn_global' => 'TURALIK-XT46',
                'wh' => 'OTS1',
                'uoi' => 'LITR'
            ],
            [
                'stock_code' => '000005009',
                'price_code' => 'FP',
                'item_name' => 'LUBRICATING OIL, GEAR',
                'class' => 'I',
                'current_class' => 'I',
                'mnemonic_current' => 'PERTAMIN',
                'pn_current' => 'SAE30 MEDITRAN',
                'pn_global' => 'SAE30 MEDITRAN',
                'wh' => 'OTS1',
                'uoi' => 'LITR'
            ],
            [
                'stock_code' => '000030635',
                'price_code' => 'FP',
                'item_name' => 'O RING',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'KOMATSU',
                'pn_current' => 'Duplikasi Pref',
                'pn_global' => '07002-03634',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000313726',
                'price_code' => 'FP',
                'item_name' => 'O-RING',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'KOMATSU',
                'pn_current' => '723-46-41950',
                'pn_global' => '723-46-41950',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000477547',
                'price_code' => 'FP',
                'item_name' => 'SCOTCHLITE RED',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => '3M',
                'pn_current' => '610-72,600X45700',
                'pn_global' => '610-72,600X45700',
                'wh' => 'SPUT',
                'uoi' => 'ROLL'
            ],
            [
                'stock_code' => '000477521',
                'price_code' => 'FP',
                'item_name' => 'SCOTCHLITE WHITE',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => '3M',
                'pn_current' => '610-10,600X45700',
                'pn_global' => '610-10,600X45700',
                'wh' => 'SPUT',
                'uoi' => 'ROLL'
            ],
            [
                'stock_code' => '000352302',
                'price_code' => 'FP',
                'item_name' => 'CAB CORNER',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '2165863',
                'pn_global' => '2165863',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000203992',
                'price_code' => 'FP',
                'item_name' => 'CAB CORNER LH',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1856473',
                'pn_global' => '1856473',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000059485',
                'price_code' => 'FP',
                'item_name' => 'SCREW',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1306573',
                'pn_global' => '1306573',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000258053',
                'price_code' => 'FP',
                'item_name' => 'LINK',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '2147948',
                'pn_global' => '2147948',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000306266',
                'price_code' => 'FP',
                'item_name' => 'HOSE',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'KOMATSU',
                'pn_current' => '20Y-62-43870',
                'pn_global' => '20Y-62-43870',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000381335',
                'price_code' => 'FP',
                'item_name' => 'LUBE FILTER',
                'class' => 'C',
                'current_class' => 'C',
                'mnemonic_current' => 'Berat Anda',
                'pn_current' => 'LF3730',
                'pn_global' => 'LF3730',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000623488',
                'price_code' => 'FP',
                'item_name' => 'REPAIR KIT',
                'class' => 'V',
                'current_class' => 'V',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '2731875',
                'pn_global' => '2731875',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000085975',
                'price_code' => 'FP',
                'item_name' => 'FILTER,LIGHT,TELESCOPIC INSTRUMENT',
                'class' => 'V',
                'current_class' => 'V',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '2003505',
                'pn_global' => '2003505',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000132019',
                'price_code' => 'FP',
                'item_name' => 'CRANKCASE VENTILATION FILTER',
                'class' => 'V',
                'current_class' => 'V',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1539675',
                'pn_global' => '1539675',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000359174',
                'price_code' => 'FP',
                'item_name' => 'PUMP ASSY',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'KOMATSU',
                'pn_current' => '708-2L-00500',
                'pn_global' => '708-2L-00500',
                'wh' => 'UTVH',
                'uoi' => 'ASSY'
            ],
            [
                'stock_code' => '000756031',
                'price_code' => 'FP',
                'item_name' => 'CHEMICAL AGENT',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'SUPERCT',
                'pn_current' => 'SUPERCOAT',
                'pn_global' => 'SUPERCOAT',
                'wh' => 'SPUT',
                'uoi' => 'LITR'
            ],
            [
                'stock_code' => '000248450',
                'price_code' => 'FP',
                'item_name' => 'PLATE STEEL',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'KS',
                'pn_current' => 'MS,10X1200X2400',
                'pn_global' => 'MS,10X1200X2400',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000371708',
                'price_code' => 'FP',
                'item_name' => 'HELMET SAFETY',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'MSA',
                'pn_current' => '226000GY',
                'pn_global' => '226000GY',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000248815',
                'price_code' => 'FP',
                'item_name' => 'PIPA GALVANIS',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'KS',
                'pn_current' => 'GL-SMLS,4"X6M,SCH40',
                'pn_global' => 'GL-SMLS,4"X6M,SCH40',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000248682',
                'price_code' => 'FP',
                'item_name' => 'BESI UNP',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'KS',
                'pn_current' => 'UNP 15,150X75X6.5X6000',
                'pn_global' => 'UNP 15,150X75X6.5X6000',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000248351',
                'price_code' => 'FP',
                'item_name' => 'BESI H-BIEM',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'KS',
                'pn_current' => '250X250X9X14X6000',
                'pn_global' => '250X250X9X14X6000',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000371856',
                'price_code' => 'FP',
                'item_name' => 'APAR POWDER 3.5 KG REFILL',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'SAFEQUIP',
                'pn_current' => '325000000 H115',
                'pn_global' => '325000000 H115',
                'wh' => 'SPUT',
                'uoi' => 'BOTL'
            ],
            [
                'stock_code' => '000371799',
                'price_code' => 'FP',
                'item_name' => 'APAR POWDER 4.5 KG REFILL',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'SAFEQUIP',
                'pn_current' => '325000000 H109',
                'pn_global' => '325000000 H109',
                'wh' => 'SPUT',
                'uoi' => 'BOTL'
            ],
            [
                'stock_code' => '000371765',
                'price_code' => '',
                'item_name' => 'APAR POWDER 9 KG REFILL',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'SAFEQUIP',
                'pn_current' => '325000000 H106',
                'pn_global' => '325000000 H106',
                'wh' => 'SPUT',
                'uoi' => 'BOTL'
            ],
            [
                'stock_code' => '000371773',
                'price_code' => 'FP',
                'item_name' => 'APAR POWDER 6 KG REFILL',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'SAFEQUIP',
                'pn_current' => '325000000 H107',
                'pn_global' => '325000000 H107',
                'wh' => 'SPUT',
                'uoi' => 'BOTL'
            ],
            [
                'stock_code' => '000098024',
                'price_code' => '',
                'item_name' => 'LAMP, CATRIDGE',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'PHILIPS',
                'pn_current' => 'AR8215-1000W',
                'pn_global' => 'AR8215-1000W',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000735068',
                'price_code' => 'FP',
                'item_name' => 'PLATE,T',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'MERLO',
                'pn_current' => '038136',
                'pn_global' => '038136',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000735050',
                'price_code' => 'FP',
                'item_name' => 'SLIDING BLOCK,T-SLOT',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'MERLO',
                'pn_current' => '094453',
                'pn_global' => '094453',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000094584',
                'price_code' => 'FP',
                'item_name' => 'WEAR PAD,BOOM',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'MERLO',
                'pn_current' => '052416',
                'pn_global' => '052416',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000094575',
                'price_code' => 'FP',
                'item_name' => 'PLATE,RETAINING,WINDOW',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'MERLO',
                'pn_current' => '053589',
                'pn_global' => '053589',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000270835',
                'price_code' => 'FP',
                'item_name' => 'CROSSLINK BRACKET',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1508403',
                'pn_global' => '1508403',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000443135',
                'price_code' => 'FP',
                'item_name' => 'CASING',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1854995',
                'pn_global' => 'Duplikasi Pref',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000203984',
                'price_code' => 'FP',
                'item_name' => 'WASHER',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1324793',
                'pn_global' => '1324793',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000723882',
                'price_code' => 'FP',
                'item_name' => 'GEAR AND SHAFT ASSEMBLY,BEVEL',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1907750',
                'pn_global' => '1907750',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000049304',
                'price_code' => 'FP',
                'item_name' => 'SPACING SLEEVE',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1343135',
                'pn_global' => '1343135',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000453084',
                'price_code' => 'FP',
                'item_name' => 'PIN',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'KOMATSU',
                'pn_current' => '04205-30828',
                'pn_global' => '04205-30828',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000298232',
                'price_code' => 'FP',
                'item_name' => 'GASKET',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'KOMATSU',
                'pn_current' => '6754-11-7120',
                'pn_global' => '6754-11-7120',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000317792',
                'price_code' => 'FP',
                'item_name' => 'DAMPER',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'KOMATSU',
                'pn_current' => '20Y-54-71181',
                'pn_global' => '20Y-54-71181',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000688846',
                'price_code' => 'FP',
                'item_name' => '*PI* FLANGE SCREW',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '2226177',
                'pn_global' => '2226177',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000350025',
                'price_code' => 'FP',
                'item_name' => 'PLUG',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '2006530',
                'pn_global' => '2006530',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000208157',
                'price_code' => 'FP',
                'item_name' => 'BRACKET LH',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1850267',
                'pn_global' => '1850267',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000368241',
                'price_code' => 'FP',
                'item_name' => 'Bracket',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1850268',
                'pn_global' => '1850268',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000440271',
                'price_code' => 'FP',
                'item_name' => 'DOOR TRIM PANEL ASS\'Y',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '2123220',
                'pn_global' => '2123220',
                'wh' => 'UTVH',
                'uoi' => 'ASSY'
            ],
            [
                'stock_code' => '000232413',
                'price_code' => 'FP',
                'item_name' => 'PLUG',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1724896',
                'pn_global' => '1724896',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000357913',
                'price_code' => 'FP',
                'item_name' => 'CAP RH',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1900182',
                'pn_global' => 'Duplikasi Pref',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000254607',
                'price_code' => 'FP',
                'item_name' => 'DOOR STOP',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1930649',
                'pn_global' => '1930649',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000161463',
                'price_code' => 'FP',
                'item_name' => 'SEAL',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1530766',
                'pn_global' => '1530766',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000419663',
                'price_code' => 'FP',
                'item_name' => 'FRAME RH',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1724880',
                'pn_global' => '1724880',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000359661',
                'price_code' => 'FP',
                'item_name' => 'HINGE PIN',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '2125180',
                'pn_global' => '2125180',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000178509',
                'price_code' => 'FP',
                'item_name' => 'MUD GUARD',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1390747',
                'pn_global' => '1390747',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000608521',
                'price_code' => 'FP',
                'item_name' => 'SEGEL',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'SINWA',
                'pn_current' => 'SMSEN03B',
                'pn_global' => 'SMSEN03B',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000626515',
                'price_code' => 'FP',
                'item_name' => 'FUEL PRO ELEMENT, FILTER',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'FLEETGRD',
                'pn_current' => 'FS 19764',
                'pn_global' => 'FS 19764',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000263277',
                'price_code' => '',
                'item_name' => 'SEAL KIT',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'AMCO',
                'pn_current' => '5.55.0709',
                'pn_global' => '5.55.0709',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000163840',
                'price_code' => 'NM',
                'item_name' => 'SEAL KIT',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'AMCO',
                'pn_current' => '5.55.0746',
                'pn_global' => '5.55.0746',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000739144',
                'price_code' => '',
                'item_name' => 'SEAL KIT',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'AMCO',
                'pn_current' => '5.55.0717',
                'pn_global' => '5.55.0717',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000163857',
                'price_code' => 'NM',
                'item_name' => 'SEAL KIT',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'AMCO',
                'pn_current' => '5.55.0722',
                'pn_global' => '5.55.0722',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000251629',
                'price_code' => '',
                'item_name' => 'SEAL KIT',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'AMCO',
                'pn_current' => '5.55.0631',
                'pn_global' => '5.55.0631',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000663443',
                'price_code' => '',
                'item_name' => 'CONTROL VALVE',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'AMCO',
                'pn_current' => '5.22.5031',
                'pn_global' => '5.22.5031',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000345793',
                'price_code' => 'FP',
                'item_name' => 'O-RING',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'KOMATSU',
                'pn_current' => '20Y-60-31430',
                'pn_global' => '20Y-60-31430',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000347674',
                'price_code' => 'FP',
                'item_name' => 'O-RING',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'KOMATSU',
                'pn_current' => '723-46-17530',
                'pn_global' => '723-46-17530',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000360230',
                'price_code' => 'FP',
                'item_name' => 'O-RING',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'KOMATSU',
                'pn_current' => '723-11-18150',
                'pn_global' => '723-11-18150',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000069054',
                'price_code' => 'FP',
                'item_name' => 'O-RING',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'KOMATSU',
                'pn_current' => '07430-71380',
                'pn_global' => '07430-71380',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000152199',
                'price_code' => 'FP',
                'item_name' => 'ROD',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'KOMATSU',
                'pn_current' => '6150-82-8610',
                'pn_global' => '6150-82-8610',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000552471',
                'price_code' => 'FP',
                'item_name' => 'BRACKET',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'KOMATSU',
                'pn_current' => '20Y-54-75930',
                'pn_global' => '20Y-54-75930',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000441469',
                'price_code' => 'FP',
                'item_name' => 'LOCK ASSY',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'KOMATSU',
                'pn_current' => '20Y-54-73190',
                'pn_global' => '20Y-54-73190',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000099607',
                'price_code' => 'FP',
                'item_name' => 'TRANSMISSION,HYDRAULIC',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'KOMATSU',
                'pn_current' => 'RC714-12-10011',
                'pn_global' => 'RC714-12-10011',
                'wh' => 'UTVH',
                'uoi' => 'ASSY'
            ],
            [
                'stock_code' => '000391896',
                'price_code' => '',
                'item_name' => 'CABLE WELDING',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'CIGWELD',
                'pn_current' => '7901224',
                'pn_global' => '7901224',
                'wh' => 'SPUT',
                'uoi' => 'M'
            ],
            [
                'stock_code' => '000745158',
                'price_code' => 'FP',
                'item_name' => 'LAMP ASSEMBLY',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'PHILIPS',
                'pn_current' => 'BVP174 LED95/CW 100W',
                'pn_global' => 'BVP174 LED95/CW 100W',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000740274',
                'price_code' => 'FP',
                'item_name' => 'LAMP ASSEMBLY',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'PHILIPS',
                'pn_current' => 'BVP176 LED190-CW 200 W',
                'pn_global' => 'BVP176 LED190-CW 200 W',
                'wh' => 'SPUT',
                'uoi' => 'ASSY'
            ],
            [
                'stock_code' => '000740275',
                'price_code' => 'FP',
                'item_name' => 'LAMP ASSEMBLY',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'PHILIPS',
                'pn_current' => 'BVP176 LED190-CW 200 W',
                'pn_global' => 'BVP176 LED190-CW 200 W',
                'wh' => 'SPUT',
                'uoi' => 'ASSY'
            ],
            [
                'stock_code' => '000393876',
                'price_code' => 'FP',
                'item_name' => 'ADAPTER',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'KOMATSU',
                'pn_current' => '6732-81-3170',
                'pn_global' => '6732-81-3170',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000381855',
                'price_code' => 'FP',
                'item_name' => 'WASHER',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'KOMATSU',
                'pn_current' => '6754-71-5350',
                'pn_global' => '6754-71-5350',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000413781',
                'price_code' => 'FP',
                'item_name' => 'HOSE',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'KOMATSU',
                'pn_current' => '20Y-62-52350',
                'pn_global' => '20Y-62-52350',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000413782',
                'price_code' => 'FP',
                'item_name' => 'HOSE',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'KOMATSU',
                'pn_current' => '07097-21217',
                'pn_global' => '07097-21217',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000358036',
                'price_code' => '',
                'item_name' => 'HOSE',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'MANULI',
                'pn_current' => '16-MULTITEX',
                'pn_global' => '16-MULTITEX',
                'wh' => 'PSVH',
                'uoi' => 'CM'
            ],
            [
                'stock_code' => '000373506',
                'price_code' => '',
                'item_name' => 'SERVICE RELAY VALVE',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'PATRIA',
                'pn_current' => 'VP001-02980',
                'pn_global' => 'VP001-02980',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000379396',
                'price_code' => '',
                'item_name' => 'R-12P RELAY VALVE (ZERO DIFF)',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'PATRIA',
                'pn_current' => 'VRBE03-90003',
                'pn_global' => 'VRBE03-90003',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000336784',
                'price_code' => 'FP',
                'item_name' => 'LOCK BRACKET',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1815227',
                'pn_global' => '1815227',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000289272',
                'price_code' => 'FP',
                'item_name' => 'INSERT CONNECTOR',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1490086',
                'pn_global' => '1490086',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000422477',
                'price_code' => 'FP',
                'item_name' => 'DRAGLINK',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '2007276',
                'pn_global' => '2007276',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000732099',
                'price_code' => 'FP',
                'item_name' => 'CHEMICAL KIT,WATER PURIFICATION',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'AMOLE',
                'pn_current' => '8850K',
                'pn_global' => '8850K',
                'wh' => 'SPUT',
                'uoi' => 'PAIL'
            ],
            [
                'stock_code' => '000732100',
                'price_code' => 'FP',
                'item_name' => 'CHEMICAL KIT, WATER PURIFICATION',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'AMOLE',
                'pn_current' => '8850K',
                'pn_global' => '8850K',
                'wh' => 'SPUT',
                'uoi' => 'PAIL'
            ],
            [
                'stock_code' => '000732101',
                'price_code' => 'FP',
                'item_name' => 'CHEMICAL KIT, WATER PURIFICATION',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'AMOLE',
                'pn_current' => '8850K',
                'pn_global' => '8850K',
                'wh' => 'SPUT',
                'uoi' => 'PAIL'
            ],
            [
                'stock_code' => '000770362',
                'price_code' => 'FP',
                'item_name' => 'WATER TREATMENT COMPOUND,BIOLOGICAL',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'FOCUS',
                'pn_current' => 'SODA ASH DENSE',
                'pn_global' => 'SODA ASH DENSE',
                'wh' => 'SPUT',
                'uoi' => 'KG'
            ],
            [
                'stock_code' => '000083707',
                'price_code' => 'FP',
                'item_name' => 'CHAMBER,CABLE TERMINAL',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1446827',
                'pn_global' => '1446827',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000267278',
                'price_code' => 'FP',
                'item_name' => 'LOCK LH',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1787674',
                'pn_global' => '1787674',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000271072',
                'price_code' => 'FP',
                'item_name' => 'WASHER',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1484054',
                'pn_global' => '1484054',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000769802',
                'price_code' => 'FP',
                'item_name' => 'STORAGE SECTION',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1437233',
                'pn_global' => '1437233',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000349464',
                'price_code' => 'FP',
                'item_name' => 'STRAP PIN',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1899302',
                'pn_global' => 'Duplikasi Pref',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000421438',
                'price_code' => 'FP',
                'item_name' => 'SEPARATOR INSERT',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1398636',
                'pn_global' => '1398636',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000362863',
                'price_code' => 'FP',
                'item_name' => 'SEPARATOR INSERT',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1747506',
                'pn_global' => 'Duplikasi Pref',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000320168',
                'price_code' => 'FP',
                'item_name' => 'BAND CLAMP',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1401840',
                'pn_global' => '1401840',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000263756',
                'price_code' => 'FP',
                'item_name' => 'CASKET',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1493434',
                'pn_global' => '1493434',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000426676',
                'price_code' => '',
                'item_name' => 'BACKPLATE',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'PATRIA',
                'pn_current' => 'SGD004',
                'pn_global' => 'SGD004',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000607432',
                'price_code' => 'FP',
                'item_name' => 'GLASS',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'KOMATSU',
                'pn_current' => '20Y-53-11841',
                'pn_global' => '20Y-53-11841',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000281758',
                'price_code' => '',
                'item_name' => 'SHAFT',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'PATRIA',
                'pn_current' => 'SED015',
                'pn_global' => 'SED015',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000230656',
                'price_code' => '',
                'item_name' => 'OIL SEAL',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'NOK',
                'pn_current' => 'TC 44 58 10',
                'pn_global' => 'TC 44 58 10',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000210799',
                'price_code' => '',
                'item_name' => 'MECHANICAL SEAL',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'PATRIA',
                'pn_current' => 'SED 021',
                'pn_global' => 'SED 021',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000433003',
                'price_code' => '',
                'item_name' => 'NUT',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'PATRIA',
                'pn_current' => 'SED046',
                'pn_global' => 'SED046',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000432997',
                'price_code' => '',
                'item_name' => 'KEY',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'PATRIA',
                'pn_current' => 'WOODRUFF BS808',
                'pn_global' => 'WOODRUFF BS808',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000286187',
                'price_code' => '',
                'item_name' => 'AIR BREATHER',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'HYVA',
                'pn_current' => '08102116',
                'pn_global' => '08102116',
                'wh' => 'SPUT',
                'uoi' => 'ASSY'
            ],
            [
                'stock_code' => '000062489',
                'price_code' => 'FP',
                'item_name' => 'GREASE PUMP',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'VOGEL',
                'pn_current' => 'KFG5-5',
                'pn_global' => 'KFG5-5',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000235929',
                'price_code' => 'FP',
                'item_name' => 'SPLIT PIN',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '805467',
                'pn_global' => '805467',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '805467',
                'price_code' => 'FP',
                'item_name' => 'NUT',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '157837',
                'pn_global' => '157837',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000082756',
                'price_code' => '',
                'item_name' => 'HOLLOW BAR, METALLIC:',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'KS',
                'pn_current' => 'HOLLOW 40X60X6000X2',
                'pn_global' => 'HOLLOW 40X60X6000X2',
                'wh' => 'SPUT',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000276220',
                'price_code' => 'FP',
                'item_name' => 'RETURN SPRING',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '1309465',
                'pn_global' => '1309465',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000617530',
                'price_code' => 'FP',
                'item_name' => 'SCREW PLUG',
                'class' => 'G',
                'current_class' => 'G',
                'mnemonic_current' => 'SCANIA',
                'pn_current' => '0813204',
                'pn_global' => '0813204',
                'wh' => 'UTVH',
                'uoi' => 'EACH'
            ],
            [
                'stock_code' => '000441253',
                'price_code' => '',
                'item_name' => 'ENGINE ASSY V1305-BG2-SAE-1',
                'class' => 'P',
                'current_class' => 'P',
                'mnemonic_current' => 'KUBOTA',
                'pn_current' => '17142-00000 V1305 BG2-SAE1',
                'pn_global' => '17142-00000 V1305 BG2-SAE1',
                'wh' => 'SPUT',
                'uoi' => 'ASSY'
            ],
        ];

        foreach ($stockdata as $item) {
            $existing = StockCode::where('stock_code', $item['stock_code'])->first();
            if (!$existing) {
                StockCode::create($item);
            }
        }
    }
}
